#!/bin/bash

# Script to display instructions for manually uploading SSH key to AWS EC2
# This is a workaround for permission issues with EB CLI

echo "===== AWS SSH Key Upload Instructions ====="
echo ""
echo "Since you're experiencing permission issues with EB CLI,"
echo "you can manually upload your SSH key to AWS EC2:"
echo ""
echo "Steps to manually upload your SSH key:"
echo "----------------------------------------"
echo "1. Go to the AWS EC2 Console:"
echo "   https://console.aws.amazon.com/ec2/"
echo ""
echo "2. In the left sidebar, under 'Network & Security', click 'Key Pairs'"
echo ""
echo "3. Click the 'Import Key Pair' button"
echo ""
echo "4. Enter a name for your key pair:"
echo "   aws-eb"
echo ""
echo "5. Copy the content of your public key file by running:"
echo "   cat ~/.ssh/aws-eb.pub"
echo ""
echo "6. Paste the copied content into the 'Public key contents' field"
echo ""
echo "7. Click 'Import Key Pair'"
echo ""
echo "8. After importing, reinitialize EB CLI:"
echo "   cd server"
echo "   eb init"
echo ""
echo "9. When prompted for SSH key, select the 'aws-eb' key you just imported"
echo ""
echo "=========================================="
echo ""
echo "This workaround avoids the permission issue"
echo "by manually handling the key import process."